/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partyprocess.client.api

import it.pagopa.pdnd.interop.uservice.partyprocess.client.model.Problem
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker._
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker.CollectionFormats._
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker.ApiKeyLocations._

object HealthApi {

  def apply(baseUrl: String = "http://localhost/pdnd-interop-uservice-party-process/}") = new HealthApi(baseUrl)
}

class HealthApi(baseUrl: String) {
  
  /**
   * Return ok
   * 
   * Expected answers:
   *   code 200 : Problem (successful operation)
   * 
   * Available security schemes:
   *   bearerAuth (http)
   */
  def getStatus()(implicit bearerToken: BearerToken): ApiRequest[Problem] =
    ApiRequest[Problem](ApiMethods.GET, baseUrl, "/status", "application/json")
      .withCredentials(bearerToken).withSuccessResponse[Problem](200)
      



}

