/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partyprocess.client.api

import it.pagopa.pdnd.interop.uservice.partyprocess.client.model.PlatformRolesResponse
import it.pagopa.pdnd.interop.uservice.partyprocess.client.model.Problem
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker._
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker.CollectionFormats._
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker.ApiKeyLocations._

object PlatformApi {

  def apply(baseUrl: String = "http://localhost/pdnd-interop-uservice-party-process/}") = new PlatformApi(baseUrl)
}

class PlatformApi(baseUrl: String) {
  
  /**
   * Returns all the available bindings between roles and platform roles.
   * 
   * Expected answers:
   *   code 200 : PlatformRolesResponse (Available platform roles' bindings.)
   *   code 400 : Problem (Bad Request)
   * 
   * Available security schemes:
   *   bearerAuth (http)
   */
  def getPlatformRoles()(implicit bearerToken: BearerToken): ApiRequest[PlatformRolesResponse] =
    ApiRequest[PlatformRolesResponse](ApiMethods.GET, baseUrl, "/platform/roles", "application/json")
      .withCredentials(bearerToken).withSuccessResponse[PlatformRolesResponse](200)
      .withErrorResponse[Problem](400)
      



}

