object Versions {
  lazy val akkaVersion                  = "2.6.15"
  lazy val akkaHttpVersion              = "10.2.4"
  lazy val partyManagementClientVersion = "0.1.0-SNAPSHOT"
  lazy val partyProxyClientVersion      = "0.1.0-SNAPSHOT"
  lazy val attributeRegistryVersion     = "0.1.0-SNAPSHOT"
  lazy val courierVersion               = "3.0.0-RC1"
  lazy val iText7Version                = "7.1.16"
  lazy val openapi4jVersion             = "1.0.7"
  lazy val json4sVersion                = "4.0.1"
  lazy val kamonVersion                 = "2.2.2"
  lazy val logbackVersion               = "1.2.4"
  lazy val scalatestVersion             = "3.2.9"
  lazy val mockitoVersion               = "3.7.7"
  lazy val scalaMockVersion             = "5.1.0"
  lazy val stateMonitoringVersion       = "0.0.3-SNAPSHOT"
  lazy val jacksonVersion               = "2.11.4"
}
