/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partyprocess.client.model

import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker.ApiModel

case class OnboardingData (
  institutionId: String,
  description: String,
  digitalAddress: String,
  status: String,
  role: String,
  product: Option[String] = None,
  productRole: String,
  /* set of products bound to this institution */
  institutionProducts: Seq[String],
  /* certified attributes bound to this institution */
  attributes: Seq[String]
) extends ApiModel

