/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partyprocess.client.model

import java.util.UUID
import it.pagopa.pdnd.interop.uservice.partyprocess.client.invoker.ApiModel

case class RelationshipInfo (
  id: UUID,
  from: UUID,
  /* represents the generic available role types for the relationship */
  role: RelationshipInfoEnums.Role,
  /* user role in the application context (e.g.: administrator, security user). This MUST belong to the configured set of application specific platform roles */
  productRole: String,
  status: RelationshipInfoEnums.Status
) extends ApiModel

object RelationshipInfoEnums {

  type Role = Role.Value
  type Status = Status.Value
  object Role extends Enumeration {
    val Manager = Value("Manager")
    val Delegate = Value("Delegate")
    val Operator = Value("Operator")
  }

  object Status extends Enumeration {
    val Pending = Value("pending")
    val Active = Value("active")
    val Inactive = Value("inactive")
  }

}
