#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

repository=$DOCKER_REPO
replicas=$REPLICAS_NR

## Setting up env vars for roles
storageType=$STORAGE_TYPE
storageContainer=$STORAGE_CONTAINER
storageEndpoint=$STORAGE_ENDPOINT

mailTemplatePath=$MAIL_TEMPLATE_PATH
mailOnboardingConfirmationLink=$MAIL_ONBOARDING_CONFIRMATION_LINK
mailOnboardingRejectionLink=$MAIL_ONBOARDING_REJECTION_LINK

mailSenderAddress=$MAIL_SENDER_ADDRESS
smtpAddress=$SMTP_HOST
smtpPort=$SMTP_PORT
smtpSSL=$SMTP_SSL
wellKnownURL=$WELL_KNOWN_URL

partyManagementVersion="0.1"
partyProxyVersion="0.1"
attributeRegistryVersion="0.1"
userRegistryManagementVersion="0.1"

partyManagementUrl="http://pdnd-interop-uservice-party-management.pdnd-interop-uservice-party-management.svc.cluster.local:8088/pdnd-interop-uservice-party-management/"$partyManagementVersion
partyProxyUrl="http://pdnd-interop-uservice-party-registry-proxy.pdnd-interop-uservice-party-registry-proxy.svc.cluster.local:8088/pdnd-interop-uservice-party-registry-proxy/"$partyProxyVersion
attributeRegistryUrl="http://pdnd-interop-uservice-attribute-registry-management.pdnd-interop-uservice-attribute-registry-management.svc.cluster.local:8088/pdnd-interop-uservice-attribute-registry-management/"$attributeRegistryVersion
userRegistryManagementUrl="http://pdnd-interop-uservice-user-registry-management.pdnd-interop-uservice-user-registry-management.svc.cluster.local:8088/pdnd-interop-uservice-user-registry-management/"$userRegistryManagementVersion

euListOfTrustedListsURL=$EU_LIST_OF_TRUSTED_LISTS_URL
euOfficialJournalUrl=$EU_OFFICIAL_JOURNAL_URL

name=$(cat $SCRIPT_PATH/../build.sbt | grep "name :=" | awk -F:= '{ print $2 }' | sed 's/\"//' | sed 's/\",//' | sed 's/ //' | tr '[:upper:]' '[:lower:]' | grep -v client)

#getting version from sbt
cd $SCRIPT_PATH/..
version=$(sbt -Dsbt.log.noformat=true 'inspect actual version' | grep "Setting: java.lang.String" | cut -d '=' -f2 | tr -d ' ')
cd $SCRIPT_PATH